(()=>{
const $=id=>document.getElementById(id),avatars=Array.from({length:102},(_,i)=>`assets/avatars/testa${i+1}.png`),chars=[['Tommaso','tommi.png','Founder'],['Giampaolo','giampa.png','Founder'],['Paolo','bretto.png','Founder'],['Davide','dave.png','Videomaker Senior'],['Tobias','tobi.png','Editor Junior'],['Luca','rabe.png','Videomaker Senior'],['Giulia','giulia.png','Editor Senior'],['Laura','laura.png','Grafica Senior'],['Guido','guido.png','Grafico Junior'],['Iris','iris.png','Producer Junior'],['Cristina','tosatto.png','Producer Senior'],['Rachele','rache.png','Producer Senior']];
const norm=v=>String(v||'').trim().toLocaleLowerCase('it');let chosenAvatar=avatars[0],charPos=0;
function current(){try{return JSON.parse(localStorage.getItem('arcade_current_user'))}catch{return null}}function guest(){const u=current();return !(u?.account||(u?.username&&!u.username.startsWith('GUEST_')))}
function overlay(id,html){let node=$(id);if(!node){node=document.createElement('div');node.id=id;node.className='flow-overlay';document.body.append(node)}node.innerHTML=`<section class="flow-card">${html}</section>`;node.hidden=false;return node}function close(id){const n=$(id);if(n)n.hidden=true}
function accountChoice(){overlay('account-choice',`<h2>VUOI ENTRARE NELLA<br>CLASSIFICA MONDIALE<br>O RESTARE NELL’OMBRA?</h2><button id="create-account" class="flow-primary">CREA ACCOUNT</button><button id="stay-anon" class="flow-secondary">RESTA ANONIMO</button>`);$('stay-anon').onclick=()=>close('account-choice');$('create-account').onclick=accountForm}
function accountForm(){overlay('account-choice',`<h2>CREA IL TUO ACCOUNT</h2><p>La mail sarà la tua unica credenziale di accesso: ricontrollala bene.</p><form id="account-form"><label>NICKNAME</label><input id="new-nickname" maxlength="18" required><label>AVATAR</label><div id="flow-avatars" class="flow-avatars"></div><label>MAIL DI ACCESSO</label><input id="new-email" autocapitalize="none" required><label>CONFERMA MAIL</label><input id="new-email-confirm" autocapitalize="none" required><p id="account-error" class="flow-error"></p><button class="flow-primary">CREA ACCOUNT</button><button type="button" id="account-back" class="flow-secondary">INDIETRO</button></form>`);renderAvatars();$('account-back').onclick=accountChoice;$('account-form').onsubmit=register}
function renderAvatars(){const grid=$('flow-avatars');grid.innerHTML=avatars.map((a,i)=>`<button type="button" class="flow-avatar ${a===chosenAvatar?'selected':''}" data-i="${i}"><img src="${a}" alt="Avatar ${i+1}"></button>`).join('');grid.onclick=e=>{const b=e.target.closest('[data-i]');if(!b)return;chosenAvatar=avatars[+b.dataset.i];renderAvatars()}}
async function register(e){e.preventDefault();const nickname=$('new-nickname').value.trim(),email=norm($('new-email').value),confirm=norm($('new-email-confirm').value),button=e.submitter;$('account-error').textContent='';if(email!==confirm){$('account-error').textContent='Le due mail non coincidono.';return}button.disabled=true;try{const character=localStorage.getItem('arcade_hub_character')||'tommi.png',r=await fetch(`${SUPABASE_URL}/functions/v1/register-account`,{method:'POST',headers:{'Content-Type':'application/json',apikey:SUPABASE_ANON_KEY},body:JSON.stringify({nickname,email,avatar:chosenAvatar,character})}),data=await r.json();if(!r.ok||!data.success)throw Error(data.error||'Registrazione non riuscita');await supabaseClient.auth.setSession({access_token:data.session.access_token,refresh_token:data.session.refresh_token});const registeredUser={...data.user,email,account:true};localStorage.setItem('arcade_current_user',JSON.stringify(registeredUser));auth.currentUser=registeredUser;close('account-choice');updateHeaderDOM();openProfileModal()}catch(x){$('account-error').textContent=x.message}finally{button.disabled=false}}
function characterPicker(){const saved=localStorage.getItem('arcade_hub_character'),at=chars.findIndex(c=>c[1]===saved);charPos=at<0?0:at;drawCharacter()}
function drawCharacter(){const c=chars[charPos],poses={'iris.png':'iris_frontale.png','rabe.png':'rabe_frontale.png','laura.png':'laura_frontale.png'},pose=poses[c[1]],src=pose?`assets/hub/pose/${pose}`:`assets/hub/player/${c[1]}`;overlay('character-picker',`<div class="flow-picker-title">CHI VUOI USARE<br>DI ACTING?</div><div class="flow-char-row"><button id="flow-prev" aria-label="Precedente">‹</button><article><div class="flow-char-preview ${pose?'square-frame':''}"><img class="${pose?'pose-animated':''}" src="${src}" alt="${c[0]}"></div><h2>${c[0]}</h2><p>${c[2]}</p><div class="flow-char-dots">${chars.map((_,i)=>`<i class="${i===charPos?'active':''}"></i>`).join('')}</div></article><button id="flow-next" aria-label="Successivo">›</button></div><button id="flow-save-char" class="flow-primary">SCEGLI</button><button id="flow-cancel-char" class="flow-secondary">ANNULLA</button>`);$('flow-prev').onclick=()=>{charPos=(charPos+chars.length-1)%chars.length;drawCharacter()};$('flow-next').onclick=()=>{charPos=(charPos+1)%chars.length;drawCharacter()};$('flow-cancel-char').onclick=()=>close('character-picker');$('flow-save-char').onclick=async()=>{localStorage.setItem('arcade_hub_character',c[1]);localStorage.setItem('arcade_hub_character_name',c[0]);if(!guest())await updateAccount({character:c[1]});sessionStorage.setItem('arcade_allow_hub','1');location.reload()}}
async function updateAccount(changes){const r=await fetch(`${SUPABASE_URL}/functions/v1/update-account`,{method:'POST',headers:{'Content-Type':'application/json',apikey:SUPABASE_ANON_KEY,authorization:`Bearer ${(await supabaseClient.auth.getSession()).data.session?.access_token||''}`},body:JSON.stringify(changes)}),data=await r.json();if(!r.ok)throw Error(data.error||'Modifica non riuscita');return data}
window.updateArcadeAccount=updateAccount;
function addProfileActions(){const tabs=document.querySelector('.profile-tabs');if(!tabs||$('change-acting-character'))return;const char=document.createElement('button');char.id='change-acting-character';char.className='auth-btn profile-character-button';char.textContent='CAMBIA PERSONAGGIO DI ACTING';char.onclick=characterPicker;tabs.before(char)}
const header=$('header-user-btn');header.addEventListener('click',e=>{if(!guest())return;e.stopImmediatePropagation();accountForm()},true);if(guest())header.textContent='👤 LOGIN';
const originalOpen=window.openProfileModal;window.openProfileModal=function(){if(guest())return accountForm();originalOpen?.();addProfileActions()};
function showGamePointer(){if(document.querySelector('.game-pointer'))return;const tip=document.createElement('div');tip.className='game-pointer';tip.innerHTML='<img src="assets/hub/freccia_giocare.png" alt="Per giocare, vai a destra">';($('game-wrapper')||document.body).append(tip);setTimeout(()=>tip.remove(),5000)}
const storyModal=$('intro-story-modal'),storyObserver=new MutationObserver(()=>{if(storyModal.style.display==='none'&&localStorage.getItem('arcade_hub_intro_seen')==='true')showGamePointer()});storyObserver.observe(storyModal,{attributes:true,attributeFilter:['style']});
if(localStorage.getItem('arcade_game_pending')==='true'){localStorage.removeItem('arcade_game_pending');if(guest())setTimeout(accountChoice,700)}
addProfileActions();
let hiddenAt=0;addEventListener('pageshow',event=>{if(event.persisted)location.replace('./start.html')});document.addEventListener('visibilitychange',()=>{if(document.hidden){hiddenAt=Date.now()}else if(hiddenAt&&Date.now()-hiddenAt>10000){location.replace('./start.html')}});
})();
