const chars=[['Tommaso','tommi.png','Founder'],['Giampaolo','giampa.png','Founder'],['Paolo','bretto.png','Founder'],['Davide','dave.png','Videomaker Senior'],['Tobias','tobi.png','Editor Junior'],['Luca','rabe.png','Videomaker Senior'],['Giulia','giulia.png','Editor Senior'],['Laura','laura.png','Grafica Senior'],['Guido','guido.png','Grafico Junior'],['Iris','iris.png','Producer Junior'],['Cristina','tosatto.png','Producer Senior'],['Rachele','rache.png','Producer Senior']].map(([name,file,role])=>({name,file,role}));
const $=id=>document.getElementById(id),norm=v=>String(v||'').trim().toLocaleLowerCase('it');let pos=0,promptEvent;
const poseFiles={"iris.png":"iris_frontale.png","rabe.png":"rabe_frontale.png","laura.png":"laura_frontale.png"};
Promise.allSettled(chars.map(character=>new Promise(resolve=>{const image=new Image();image.onload=image.onerror=resolve;image.src=poseFiles[character.file]?`assets/hub/pose/${poseFiles[character.file]}`:`assets/hub/player/${character.file}`})));
function user(){try{return JSON.parse(localStorage.getItem('arcade_current_user'))}catch{return null}}function account(){const u=user();return !!(u?.account||(u?.username&&!u.username.startsWith('GUEST_')))}
function screen(id){document.querySelectorAll('.screen').forEach(e=>e.classList.toggle('active',e.id===id))}
function enterHub(){sessionStorage.setItem('arcade_allow_hub','1');location.replace('hub/index.html')}
function landing(){const yes=account();$('actions').innerHTML=`<button id="go" class="primary">${yes?'CONTINUA':'INIZIA'}</button>${yes?'<button id="logout" class="secondary">ESCI</button>':'<button id="access" class="secondary">ACCEDI</button>'}`;$('go').onclick=()=>yes?enterHub():openChars();if(yes)$('logout').onclick=async()=>{localStorage.removeItem('arcade_current_user');localStorage.removeItem('arcade_hub_character');await supabaseClient?.auth.signOut();landing()};else $('access').onclick=()=>{$('login').hidden=false;$('login-email').focus()}}
function openChars(){if(!account()){localStorage.removeItem('arcade_player_x');localStorage.removeItem('arcade_hub_intro_seen');localStorage.removeItem('arcade_game_pending')}const saved=localStorage.getItem('arcade_hub_character'),found=chars.findIndex(c=>c.file===saved);pos=found<0?0:found;draw();screen('characters')}
function draw(){const c=chars[pos],pose=poseFiles[c.file],img=$('char-img');img.classList.remove('pose-animated');img.src=pose?`assets/hub/pose/${pose}`:`assets/hub/player/${c.file}`;img.alt=c.name;img.closest('.crop').classList.toggle('square-frame',!!pose);void img.offsetWidth;if(pose)img.classList.add('pose-animated');$('char-name').textContent=c.name;$('char-role').textContent=c.role;$('dots').innerHTML=chars.map((_,i)=>`<i class="${i===pos?'on':''}"></i>`).join('')}
function move(n){pos=(pos+n+chars.length)%chars.length;draw()}$('prev').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('back').onclick=()=>screen('landing');
$('choose').onclick=()=>{const c=chars[pos];localStorage.setItem('arcade_hub_character',c.file);localStorage.setItem('arcade_hub_character_name',c.name);if(!account()){sessionStorage.setItem('arcade_guest_session','1');localStorage.setItem('arcade_current_user',JSON.stringify({username:'GUEST_SESSION',avatar:'assets/avatars/testa1.png',stats:{},guest:true}))}enterHub()};let sx=0;$('characters').onpointerdown=e=>sx=e.clientX;$('characters').onpointerup=e=>{if(Math.abs(e.clientX-sx)>45)move(e.clientX>sx?-1:1)};
$('login-x').onclick=()=>$('login').hidden=true;$('login-form').onsubmit=async e=>{e.preventDefault();const email=norm($('login-email').value),btn=e.submitter;btn.disabled=true;$('login-error').textContent='';try{const r=await fetch(`${SUPABASE_URL}/functions/v1/login-account`,{method:'POST',headers:{'Content-Type':'application/json',apikey:SUPABASE_ANON_KEY},body:JSON.stringify({email})}),data=await r.json();if(!r.ok||!data.success)throw Error(data.error||'Account non trovato');await supabaseClient.auth.setSession({access_token:data.session.access_token,refresh_token:data.session.refresh_token});localStorage.setItem('arcade_current_user',JSON.stringify({...data.user,email,account:true}));if(data.user.character)localStorage.setItem('arcade_hub_character',data.user.character);enterHub()}catch(x){$('login-error').textContent=x.message}finally{btn.disabled=false}};
function standalone(){return matchMedia('(display-mode:standalone)').matches||navigator.standalone===true}function install(){if(standalone())return;const ios=/iPad|iPhone|iPod/.test(navigator.userAgent);$('install-copy').innerHTML=ios?'Tocca <b>tre punti</b>, poi <b>Condividi</b>, <b>Visualizza altro</b> e <b>Aggiungi alla schermata Home</b>.':'Installa la web app e aggiungila alla schermata Home.';$('install-btn').hidden=ios||!promptEvent;$('install').hidden=false}addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;$('install-btn').hidden=false});$('install-btn').onclick=async()=>{await promptEvent?.prompt();promptEvent=null;$('install').hidden=true};$('install-x').onclick=()=>$('install').hidden=true;addEventListener('appinstalled',()=>$('install').hidden=true);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));if(user()?.guest&&!sessionStorage.getItem('arcade_guest_session')){localStorage.removeItem('arcade_current_user');localStorage.removeItem('arcade_hub_character');localStorage.removeItem('arcade_hub_intro_seen')}else{const old=user();if(old&&!old.account&&!old.username.startsWith('GUEST_')){old.account=true;old.email=norm(old.username);localStorage.setItem('arcade_current_user',JSON.stringify(old))}}landing();setTimeout(install,350);
